### ISSUE TITLE
autocompleter ignores requestType

### ISSUE THREAD

**Issue by assachs** [struts-community-plugins/struts2-jquery#133]
Hello,
autocompleter ignores requestType attribute on generating Ajax requests. It's not possible to make POST requests.

Andi

**Comment by sdutry** [comment]
@jogep 
according to the wiki-page about the `sj:autocompleter` tag, the default `requestType` attribute should be `POST`. Currently it seems to ignore the requestType and performs a `GET` request.

To fix this issue, am i supposed to make `POST` the default method, or should the documentation be updated so that `GET` becomes the default method?

- [AutocompleterTag Wikipage](https://github.com/struts-community-plugins/struts2-jquery/wiki/AutocompleterTag)

**Comment by sdutry** [comment]
@jogep 
I can't seem to find any remnant of a `requestType` attribute ever having existed for the `sj:autocompleter` tag.

Am i missing something?

**Comment by sdutry** [comment]
Note to self: check superclasses

requestType available through inheritance from:
- `com.jgeppert.struts2.jquery.views.jsp.ui.AbstractRemoteTag.java`
- `com.jgeppert.struts2.jquery.components.AbstractRemoteBean`

TODO:
- change template to use it

**Comment by sdutry** [comment]
When the autocomplete is passed a variable of type string, it executes a GET request
inside `src/main/resources/template/js/base/autocomplete.js`
```javascript
	_initSource: function() {
		var array, url,
			that = this;
		if ( $.isArray( this.options.source ) ) {
			array = this.options.source;
			this.source = function( request, response ) {
				response( $.ui.autocomplete.filter( array, request.term ) );
			};
		} else if ( typeof this.options.source === "string" ) {
			url = this.options.source;
			this.source = function( request, response ) {
				if ( that.xhr ) {
					that.xhr.abort();
				}
				that.xhr = $.ajax( {
					url: url,
					data: request,
					dataType: "json",
					success: function( data ) {
						response( data );
					},
					error: function() {
						response( [] );
					}
				} );
			};
		} else {
			this.source = this.options.source;
		}
	},
```
TODO:
Change it so that the source parameter is no longer a url but a function that performs the ajax request
`src/main/resources/template/js/struts2/jquery.ui.struts2.js`
```javascript
                else {
                    params.source = self.addForms(o.formids, url);
                }
```

**Comment by jogep** [comment]
Close issue because version 4.0.3 is released.
