### ISSUE TITLE
Struts2 jquery plugin doesn't work with CSP script-src secure

### ISSUE THREAD

**Issue by fjamores3** [struts-community-plugins/struts2-jquery#142]
I'm trying to use struts2-jquery-plugin but i can't . The reason is my content-secure-policy header against Cross Site Scripting (XSS) attacks... How can i solve it without use 'unsafe-inline' mode in script-src field?

Thanks a lot.

**Comment by sdutry** [comment]
@fjamores3 
My current knowledge about `Content Security Policy` is limited.

From my understanding, your problem is because there's a script being loaded from a different domain.

Normaly, when using the simple `sj:head` tag, all scripts should be loaded from the domain your page loads on.

```jsp
...
<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>
...
    <sj:head/>
...
```

Therefore the following questions in order to investigate further::
* How exactly does your `sj:head` tag look?
* What is the exact content of your `Content-Security-Policy` header?
* which requests are causing the issues?

**edit:** 
It appears your problem is that the CSP doesn't allow script tags to be used inside the page itself.

Given that the scripts are generated when interpreting the tag, and therefore can not be put in a seperate script file, do you have any suggestions as to how we could satisfy the requirement?

I'm seeing that CSP currently allows 2 ways of providing inline scripts:
* Adding a nonce to the script tag and having that nonce in the CSP header of the request
* Adding a hash for the script and adding it in the CSP header of the request.

Given the fact that headers need to be sent to the client first, i doubt that adding the hashes to the header is an option.

How is the CSP header being added currently? Will a CSP header sent by the application be overwritten by your current mechanism?

**Comment by marwin1991** [comment]
some solutions ?

**Comment by hymiliat** [comment]
The <sj:head/> generates <scripts> added to the html page.
Due to Struts new CSP Interceptor, all scripts must add a "nonce" parameter in order to be loaded by the browser. Thankfully, Struts also implemented a new <s:script/> tag which adds this nonce parameter automatically.

More details here: https://github.com/apache/struts/pull/430

Solution: Can you please make sure that the <sj:head> generates <s:script/> rather than <script/>? Also if any <link/> is generated, can you please change it to <s:link/>? 

Thank you very much.
