### ISSUE TITLE
Issue on sj:datepicker tag on Struts2 6.0.x version

### ISSUE THREAD

**Issue by Mori0005** [struts-community-plugins/struts2-jquery#321]
It seems i cannot get /struts/js/calendar.gif image when i use
<sj:datepicker> tag.
Would anyone help on this ?

**Comment by lukaszlenart** [comment]
I already answered your question in https://lists.apache.org/thread/j1gjsz942ko0l8g5g1glwm17boh06ml8

**Comment by Mori0005** [comment]
Hi, 
Thanks for your advice.
I understand Static content is served from /static path now.
However, the issue is sj:datepicker tag tries to get calendar.gif from /struts/js/calendar.gif.
My Struts2-jquery version is latest 5.0.1 
How can I avoid this issue ?

**Comment by lukaszlenart** [comment]
As far I see the problem is already fixed, but not released yet e49cbea88f5a40a135bf85a5ed1074820b21fd24 - you can define `buttonImage` attribute pointing to `./static/js/calendar.gif` (depending on your context use a proper prefix)
https://github.com/struts-community-plugins/struts2-jquery/wiki/DatePickerTag

**Comment by Mori0005** [comment]
Great, thx!
